// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoleProtocol.proto

package com.leader.game.protobuf.protocol;

public final class RoleProtocol {
  private RoleProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RoleInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RoleInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>optional int64 playerId = 2;</code>
     */
    long getPlayerId();

    /**
     * <code>optional int64 sectId = 3;</code>
     */
    long getSectId();

    /**
     * <code>optional int32 modelId = 4;</code>
     */
    int getModelId();

    /**
     * <code>optional string name = 5;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 5;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *等级
     * </pre>
     *
     * <code>optional int32 level = 6;</code>
     */
    int getLevel();

    /**
     * <pre>
     *修仙等阶
     * </pre>
     *
     * <code>optional int32 clazz = 7;</code>
     */
    int getClazz();

    /**
     * <pre>
     *头衔
     * </pre>
     *
     * <code>optional string title = 8;</code>
     */
    java.lang.String getTitle();
    /**
     * <pre>
     *头衔
     * </pre>
     *
     * <code>optional string title = 8;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();
  }
  /**
   * <pre>
   * 同步请求
   * </pre>
   *
   * Protobuf type {@code RoleInfo}
   */
  public  static final class RoleInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RoleInfo)
      RoleInfoOrBuilder {
    // Use RoleInfo.newBuilder() to construct.
    private RoleInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoleInfo() {
      id_ = 0L;
      playerId_ = 0L;
      sectId_ = 0L;
      modelId_ = 0;
      name_ = "";
      level_ = 0;
      clazz_ = 0;
      title_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RoleInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 16: {

              playerId_ = input.readInt64();
              break;
            }
            case 24: {

              sectId_ = input.readInt64();
              break;
            }
            case 32: {

              modelId_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 48: {

              level_ = input.readInt32();
              break;
            }
            case 56: {

              clazz_ = input.readInt32();
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leader.game.protobuf.protocol.RoleProtocol.internal_static_RoleInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leader.game.protobuf.protocol.RoleProtocol.internal_static_RoleInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo.class, com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int PLAYERID_FIELD_NUMBER = 2;
    private long playerId_;
    /**
     * <code>optional int64 playerId = 2;</code>
     */
    public long getPlayerId() {
      return playerId_;
    }

    public static final int SECTID_FIELD_NUMBER = 3;
    private long sectId_;
    /**
     * <code>optional int64 sectId = 3;</code>
     */
    public long getSectId() {
      return sectId_;
    }

    public static final int MODELID_FIELD_NUMBER = 4;
    private int modelId_;
    /**
     * <code>optional int32 modelId = 4;</code>
     */
    public int getModelId() {
      return modelId_;
    }

    public static final int NAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 5;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 5;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVEL_FIELD_NUMBER = 6;
    private int level_;
    /**
     * <pre>
     *等级
     * </pre>
     *
     * <code>optional int32 level = 6;</code>
     */
    public int getLevel() {
      return level_;
    }

    public static final int CLAZZ_FIELD_NUMBER = 7;
    private int clazz_;
    /**
     * <pre>
     *修仙等阶
     * </pre>
     *
     * <code>optional int32 clazz = 7;</code>
     */
    public int getClazz() {
      return clazz_;
    }

    public static final int TITLE_FIELD_NUMBER = 8;
    private volatile java.lang.Object title_;
    /**
     * <pre>
     *头衔
     * </pre>
     *
     * <code>optional string title = 8;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *头衔
     * </pre>
     *
     * <code>optional string title = 8;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (playerId_ != 0L) {
        output.writeInt64(2, playerId_);
      }
      if (sectId_ != 0L) {
        output.writeInt64(3, sectId_);
      }
      if (modelId_ != 0) {
        output.writeInt32(4, modelId_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, name_);
      }
      if (level_ != 0) {
        output.writeInt32(6, level_);
      }
      if (clazz_ != 0) {
        output.writeInt32(7, clazz_);
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, title_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (playerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, playerId_);
      }
      if (sectId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, sectId_);
      }
      if (modelId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, modelId_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, name_);
      }
      if (level_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, level_);
      }
      if (clazz_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, clazz_);
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, title_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo)) {
        return super.equals(obj);
      }
      com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo other = (com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getPlayerId()
          == other.getPlayerId());
      result = result && (getSectId()
          == other.getSectId());
      result = result && (getModelId()
          == other.getModelId());
      result = result && getName()
          .equals(other.getName());
      result = result && (getLevel()
          == other.getLevel());
      result = result && (getClazz()
          == other.getClazz());
      result = result && getTitle()
          .equals(other.getTitle());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPlayerId());
      hash = (37 * hash) + SECTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSectId());
      hash = (37 * hash) + MODELID_FIELD_NUMBER;
      hash = (53 * hash) + getModelId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getLevel();
      hash = (37 * hash) + CLAZZ_FIELD_NUMBER;
      hash = (53 * hash) + getClazz();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 同步请求
     * </pre>
     *
     * Protobuf type {@code RoleInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RoleInfo)
        com.leader.game.protobuf.protocol.RoleProtocol.RoleInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leader.game.protobuf.protocol.RoleProtocol.internal_static_RoleInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leader.game.protobuf.protocol.RoleProtocol.internal_static_RoleInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo.class, com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo.Builder.class);
      }

      // Construct using com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        playerId_ = 0L;

        sectId_ = 0L;

        modelId_ = 0;

        name_ = "";

        level_ = 0;

        clazz_ = 0;

        title_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leader.game.protobuf.protocol.RoleProtocol.internal_static_RoleInfo_descriptor;
      }

      public com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo getDefaultInstanceForType() {
        return com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo.getDefaultInstance();
      }

      public com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo build() {
        com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo buildPartial() {
        com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo result = new com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo(this);
        result.id_ = id_;
        result.playerId_ = playerId_;
        result.sectId_ = sectId_;
        result.modelId_ = modelId_;
        result.name_ = name_;
        result.level_ = level_;
        result.clazz_ = clazz_;
        result.title_ = title_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo) {
          return mergeFrom((com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo other) {
        if (other == com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getPlayerId() != 0L) {
          setPlayerId(other.getPlayerId());
        }
        if (other.getSectId() != 0L) {
          setSectId(other.getSectId());
        }
        if (other.getModelId() != 0) {
          setModelId(other.getModelId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getLevel() != 0) {
          setLevel(other.getLevel());
        }
        if (other.getClazz() != 0) {
          setClazz(other.getClazz());
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private long playerId_ ;
      /**
       * <code>optional int64 playerId = 2;</code>
       */
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <code>optional int64 playerId = 2;</code>
       */
      public Builder setPlayerId(long value) {
        
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 playerId = 2;</code>
       */
      public Builder clearPlayerId() {
        
        playerId_ = 0L;
        onChanged();
        return this;
      }

      private long sectId_ ;
      /**
       * <code>optional int64 sectId = 3;</code>
       */
      public long getSectId() {
        return sectId_;
      }
      /**
       * <code>optional int64 sectId = 3;</code>
       */
      public Builder setSectId(long value) {
        
        sectId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sectId = 3;</code>
       */
      public Builder clearSectId() {
        
        sectId_ = 0L;
        onChanged();
        return this;
      }

      private int modelId_ ;
      /**
       * <code>optional int32 modelId = 4;</code>
       */
      public int getModelId() {
        return modelId_;
      }
      /**
       * <code>optional int32 modelId = 4;</code>
       */
      public Builder setModelId(int value) {
        
        modelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 modelId = 4;</code>
       */
      public Builder clearModelId() {
        
        modelId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 5;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 5;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 5;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 5;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 5;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <pre>
       *等级
       * </pre>
       *
       * <code>optional int32 level = 6;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <pre>
       *等级
       * </pre>
       *
       * <code>optional int32 level = 6;</code>
       */
      public Builder setLevel(int value) {
        
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *等级
       * </pre>
       *
       * <code>optional int32 level = 6;</code>
       */
      public Builder clearLevel() {
        
        level_ = 0;
        onChanged();
        return this;
      }

      private int clazz_ ;
      /**
       * <pre>
       *修仙等阶
       * </pre>
       *
       * <code>optional int32 clazz = 7;</code>
       */
      public int getClazz() {
        return clazz_;
      }
      /**
       * <pre>
       *修仙等阶
       * </pre>
       *
       * <code>optional int32 clazz = 7;</code>
       */
      public Builder setClazz(int value) {
        
        clazz_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *修仙等阶
       * </pre>
       *
       * <code>optional int32 clazz = 7;</code>
       */
      public Builder clearClazz() {
        
        clazz_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <pre>
       *头衔
       * </pre>
       *
       * <code>optional string title = 8;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *头衔
       * </pre>
       *
       * <code>optional string title = 8;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *头衔
       * </pre>
       *
       * <code>optional string title = 8;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *头衔
       * </pre>
       *
       * <code>optional string title = 8;</code>
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *头衔
       * </pre>
       *
       * <code>optional string title = 8;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:RoleInfo)
    }

    // @@protoc_insertion_point(class_scope:RoleInfo)
    private static final com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo();
    }

    public static com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoleInfo>
        PARSER = new com.google.protobuf.AbstractParser<RoleInfo>() {
      public RoleInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RoleInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoleInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoleInfo> getParserForType() {
      return PARSER;
    }

    public com.leader.game.protobuf.protocol.RoleProtocol.RoleInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoleInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoleInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022RoleProtocol.proto\"\204\001\n\010RoleInfo\022\n\n\002id\030" +
      "\001 \001(\003\022\020\n\010playerId\030\002 \001(\003\022\016\n\006sectId\030\003 \001(\003\022" +
      "\017\n\007modelId\030\004 \001(\005\022\014\n\004name\030\005 \001(\t\022\r\n\005level\030" +
      "\006 \001(\005\022\r\n\005clazz\030\007 \001(\005\022\r\n\005title\030\010 \001(\tB1\n!c" +
      "om.leader.game.protobuf.protocolB\014RolePr" +
      "otocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RoleInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RoleInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoleInfo_descriptor,
        new java.lang.String[] { "Id", "PlayerId", "SectId", "ModelId", "Name", "Level", "Clazz", "Title", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
