// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerInternalProtocol.proto

package com.leader.game.protobuf.protocol;

public final class ServerInternal {
  private ServerInternal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReqRegisterServerMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.cytx.pokemon.server.register.ReqRegisterServerMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *服务器编号
     * </pre>
     *
     * <code>required int32 serverId = 1;</code>
     */
    boolean hasServerId();
    /**
     * <pre>
     *服务器编号
     * </pre>
     *
     * <code>required int32 serverId = 1;</code>
     */
    int getServerId();

    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *外网ip地址
     * </pre>
     *
     * <code>required string ip = 3;</code>
     */
    boolean hasIp();
    /**
     * <pre>
     *外网ip地址
     * </pre>
     *
     * <code>required string ip = 3;</code>
     */
    java.lang.String getIp();
    /**
     * <pre>
     *外网ip地址
     * </pre>
     *
     * <code>required string ip = 3;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <pre>
     *端口号
     * </pre>
     *
     * <code>required int32 port = 4;</code>
     */
    boolean hasPort();
    /**
     * <pre>
     *端口号
     * </pre>
     *
     * <code>required int32 port = 4;</code>
     */
    int getPort();
  }
  /**
   * <pre>
   *服务器注册消息
   * </pre>
   *
   * Protobuf type {@code com.cytx.pokemon.server.register.ReqRegisterServerMessage}
   */
  public  static final class ReqRegisterServerMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.cytx.pokemon.server.register.ReqRegisterServerMessage)
      ReqRegisterServerMessageOrBuilder {
    // Use ReqRegisterServerMessage.newBuilder() to construct.
    private ReqRegisterServerMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReqRegisterServerMessage() {
      serverId_ = 0;
      name_ = "";
      ip_ = "";
      port_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReqRegisterServerMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              serverId_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              ip_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              port_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leader.game.protobuf.protocol.ServerInternal.internal_static_com_cytx_pokemon_server_register_ReqRegisterServerMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leader.game.protobuf.protocol.ServerInternal.internal_static_com_cytx_pokemon_server_register_ReqRegisterServerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage.class, com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage.Builder.class);
    }

    private int bitField0_;
    public static final int SERVERID_FIELD_NUMBER = 1;
    private int serverId_;
    /**
     * <pre>
     *服务器编号
     * </pre>
     *
     * <code>required int32 serverId = 1;</code>
     */
    public boolean hasServerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *服务器编号
     * </pre>
     *
     * <code>required int32 serverId = 1;</code>
     */
    public int getServerId() {
      return serverId_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *名字
     * </pre>
     *
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 3;
    private volatile java.lang.Object ip_;
    /**
     * <pre>
     *外网ip地址
     * </pre>
     *
     * <code>required string ip = 3;</code>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *外网ip地址
     * </pre>
     *
     * <code>required string ip = 3;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ip_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *外网ip地址
     * </pre>
     *
     * <code>required string ip = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 4;
    private int port_;
    /**
     * <pre>
     *端口号
     * </pre>
     *
     * <code>required int32 port = 4;</code>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *端口号
     * </pre>
     *
     * <code>required int32 port = 4;</code>
     */
    public int getPort() {
      return port_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasServerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, serverId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ip_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, port_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serverId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ip_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, port_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage)) {
        return super.equals(obj);
      }
      com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage other = (com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage) obj;

      boolean result = true;
      result = result && (hasServerId() == other.hasServerId());
      if (hasServerId()) {
        result = result && (getServerId()
            == other.getServerId());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasIp() == other.hasIp());
      if (hasIp()) {
        result = result && getIp()
            .equals(other.getIp());
      }
      result = result && (hasPort() == other.hasPort());
      if (hasPort()) {
        result = result && (getPort()
            == other.getPort());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasServerId()) {
        hash = (37 * hash) + SERVERID_FIELD_NUMBER;
        hash = (53 * hash) + getServerId();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasIp()) {
        hash = (37 * hash) + IP_FIELD_NUMBER;
        hash = (53 * hash) + getIp().hashCode();
      }
      if (hasPort()) {
        hash = (37 * hash) + PORT_FIELD_NUMBER;
        hash = (53 * hash) + getPort();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *服务器注册消息
     * </pre>
     *
     * Protobuf type {@code com.cytx.pokemon.server.register.ReqRegisterServerMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.cytx.pokemon.server.register.ReqRegisterServerMessage)
        com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leader.game.protobuf.protocol.ServerInternal.internal_static_com_cytx_pokemon_server_register_ReqRegisterServerMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leader.game.protobuf.protocol.ServerInternal.internal_static_com_cytx_pokemon_server_register_ReqRegisterServerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage.class, com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage.Builder.class);
      }

      // Construct using com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        serverId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leader.game.protobuf.protocol.ServerInternal.internal_static_com_cytx_pokemon_server_register_ReqRegisterServerMessage_descriptor;
      }

      public com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage getDefaultInstanceForType() {
        return com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage.getDefaultInstance();
      }

      public com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage build() {
        com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage buildPartial() {
        com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage result = new com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverId_ = serverId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.port_ = port_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage) {
          return mergeFrom((com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage other) {
        if (other == com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage.getDefaultInstance()) return this;
        if (other.hasServerId()) {
          setServerId(other.getServerId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasIp()) {
          bitField0_ |= 0x00000004;
          ip_ = other.ip_;
          onChanged();
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServerId()) {
          return false;
        }
        if (!hasName()) {
          return false;
        }
        if (!hasIp()) {
          return false;
        }
        if (!hasPort()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int serverId_ ;
      /**
       * <pre>
       *服务器编号
       * </pre>
       *
       * <code>required int32 serverId = 1;</code>
       */
      public boolean hasServerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *服务器编号
       * </pre>
       *
       * <code>required int32 serverId = 1;</code>
       */
      public int getServerId() {
        return serverId_;
      }
      /**
       * <pre>
       *服务器编号
       * </pre>
       *
       * <code>required int32 serverId = 1;</code>
       */
      public Builder setServerId(int value) {
        bitField0_ |= 0x00000001;
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务器编号
       * </pre>
       *
       * <code>required int32 serverId = 1;</code>
       */
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *名字
       * </pre>
       *
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <pre>
       *外网ip地址
       * </pre>
       *
       * <code>required string ip = 3;</code>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *外网ip地址
       * </pre>
       *
       * <code>required string ip = 3;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ip_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *外网ip地址
       * </pre>
       *
       * <code>required string ip = 3;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *外网ip地址
       * </pre>
       *
       * <code>required string ip = 3;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *外网ip地址
       * </pre>
       *
       * <code>required string ip = 3;</code>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *外网ip地址
       * </pre>
       *
       * <code>required string ip = 3;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ip_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <pre>
       *端口号
       * </pre>
       *
       * <code>required int32 port = 4;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *端口号
       * </pre>
       *
       * <code>required int32 port = 4;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <pre>
       *端口号
       * </pre>
       *
       * <code>required int32 port = 4;</code>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000008;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *端口号
       * </pre>
       *
       * <code>required int32 port = 4;</code>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000008);
        port_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.cytx.pokemon.server.register.ReqRegisterServerMessage)
    }

    // @@protoc_insertion_point(class_scope:com.cytx.pokemon.server.register.ReqRegisterServerMessage)
    private static final com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage();
    }

    public static com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ReqRegisterServerMessage>
        PARSER = new com.google.protobuf.AbstractParser<ReqRegisterServerMessage>() {
      public ReqRegisterServerMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReqRegisterServerMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReqRegisterServerMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqRegisterServerMessage> getParserForType() {
      return PARSER;
    }

    public com.leader.game.protobuf.protocol.ServerInternal.ReqRegisterServerMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReqInternalHeartbeatMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.cytx.pokemon.server.register.ReqInternalHeartbeatMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *在线人数
     * </pre>
     *
     * <code>required int32 online = 1;</code>
     */
    boolean hasOnline();
    /**
     * <pre>
     *在线人数
     * </pre>
     *
     * <code>required int32 online = 1;</code>
     */
    int getOnline();
  }
  /**
   * <pre>
   *网关服注册心跳消息
   * </pre>
   *
   * Protobuf type {@code com.cytx.pokemon.server.register.ReqInternalHeartbeatMessage}
   */
  public  static final class ReqInternalHeartbeatMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.cytx.pokemon.server.register.ReqInternalHeartbeatMessage)
      ReqInternalHeartbeatMessageOrBuilder {
    // Use ReqInternalHeartbeatMessage.newBuilder() to construct.
    private ReqInternalHeartbeatMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReqInternalHeartbeatMessage() {
      online_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReqInternalHeartbeatMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              online_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leader.game.protobuf.protocol.ServerInternal.internal_static_com_cytx_pokemon_server_register_ReqInternalHeartbeatMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leader.game.protobuf.protocol.ServerInternal.internal_static_com_cytx_pokemon_server_register_ReqInternalHeartbeatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage.class, com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage.Builder.class);
    }

    private int bitField0_;
    public static final int ONLINE_FIELD_NUMBER = 1;
    private int online_;
    /**
     * <pre>
     *在线人数
     * </pre>
     *
     * <code>required int32 online = 1;</code>
     */
    public boolean hasOnline() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *在线人数
     * </pre>
     *
     * <code>required int32 online = 1;</code>
     */
    public int getOnline() {
      return online_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOnline()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, online_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, online_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage)) {
        return super.equals(obj);
      }
      com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage other = (com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage) obj;

      boolean result = true;
      result = result && (hasOnline() == other.hasOnline());
      if (hasOnline()) {
        result = result && (getOnline()
            == other.getOnline());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOnline()) {
        hash = (37 * hash) + ONLINE_FIELD_NUMBER;
        hash = (53 * hash) + getOnline();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *网关服注册心跳消息
     * </pre>
     *
     * Protobuf type {@code com.cytx.pokemon.server.register.ReqInternalHeartbeatMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.cytx.pokemon.server.register.ReqInternalHeartbeatMessage)
        com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leader.game.protobuf.protocol.ServerInternal.internal_static_com_cytx_pokemon_server_register_ReqInternalHeartbeatMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leader.game.protobuf.protocol.ServerInternal.internal_static_com_cytx_pokemon_server_register_ReqInternalHeartbeatMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage.class, com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage.Builder.class);
      }

      // Construct using com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        online_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leader.game.protobuf.protocol.ServerInternal.internal_static_com_cytx_pokemon_server_register_ReqInternalHeartbeatMessage_descriptor;
      }

      public com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage getDefaultInstanceForType() {
        return com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage.getDefaultInstance();
      }

      public com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage build() {
        com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage buildPartial() {
        com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage result = new com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.online_ = online_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage) {
          return mergeFrom((com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage other) {
        if (other == com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage.getDefaultInstance()) return this;
        if (other.hasOnline()) {
          setOnline(other.getOnline());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOnline()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int online_ ;
      /**
       * <pre>
       *在线人数
       * </pre>
       *
       * <code>required int32 online = 1;</code>
       */
      public boolean hasOnline() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *在线人数
       * </pre>
       *
       * <code>required int32 online = 1;</code>
       */
      public int getOnline() {
        return online_;
      }
      /**
       * <pre>
       *在线人数
       * </pre>
       *
       * <code>required int32 online = 1;</code>
       */
      public Builder setOnline(int value) {
        bitField0_ |= 0x00000001;
        online_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *在线人数
       * </pre>
       *
       * <code>required int32 online = 1;</code>
       */
      public Builder clearOnline() {
        bitField0_ = (bitField0_ & ~0x00000001);
        online_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.cytx.pokemon.server.register.ReqInternalHeartbeatMessage)
    }

    // @@protoc_insertion_point(class_scope:com.cytx.pokemon.server.register.ReqInternalHeartbeatMessage)
    private static final com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage();
    }

    public static com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ReqInternalHeartbeatMessage>
        PARSER = new com.google.protobuf.AbstractParser<ReqInternalHeartbeatMessage>() {
      public ReqInternalHeartbeatMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReqInternalHeartbeatMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReqInternalHeartbeatMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqInternalHeartbeatMessage> getParserForType() {
      return PARSER;
    }

    public com.leader.game.protobuf.protocol.ServerInternal.ReqInternalHeartbeatMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cytx_pokemon_server_register_ReqRegisterServerMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cytx_pokemon_server_register_ReqRegisterServerMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cytx_pokemon_server_register_ReqInternalHeartbeatMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cytx_pokemon_server_register_ReqInternalHeartbeatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034ServerInternalProtocol.proto\022 com.cytx" +
      ".pokemon.server.register\"T\n\030ReqRegisterS" +
      "erverMessage\022\020\n\010serverId\030\001 \002(\005\022\014\n\004name\030\002" +
      " \002(\t\022\n\n\002ip\030\003 \002(\t\022\014\n\004port\030\004 \002(\005\"-\n\033ReqInt" +
      "ernalHeartbeatMessage\022\016\n\006online\030\001 \002(\005B3\n" +
      "!com.leader.game.protobuf.protocolB\016Serv" +
      "erInternal"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_cytx_pokemon_server_register_ReqRegisterServerMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_cytx_pokemon_server_register_ReqRegisterServerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cytx_pokemon_server_register_ReqRegisterServerMessage_descriptor,
        new java.lang.String[] { "ServerId", "Name", "Ip", "Port", });
    internal_static_com_cytx_pokemon_server_register_ReqInternalHeartbeatMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_cytx_pokemon_server_register_ReqInternalHeartbeatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cytx_pokemon_server_register_ReqInternalHeartbeatMessage_descriptor,
        new java.lang.String[] { "Online", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
